package com.raisedeveloper.server.global.exception;

import static com.raisedeveloper.server.global.exception.ErrorMessageConstants.*;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

	// common
	// [400]
	INVALID_JSON(400, "INVALID_JSON", COMMON_INVALID_JSON_MESSAGE),
	ACCESS_DENIED(403, "ACCESS_DENIED", COMMON_ACCESS_DENIED_MESSAGE),
	RESOURCE_NOT_FOUND(404, "RESOURCE_NOT_FOUND", COMMON_RESOURCE_NOT_FOUND_MESSAGE),
	METHOD_NOT_ALLOWED(405, "METHOD_NOT_ALLOWED", COMMON_METHOD_NOT_ALLOWED_MESSAGE),
	UNSUPPORTED_MEDIA_TYPE(415, "UNSUPPORTED_MEDIA_TYPE", COMMON_UNSUPPORTED_MEDIA_TYPE_MESSAGE),
	// [405],
	VALIDATION_FAILED(422, "VALIDATION_FAILED", COMMON_VALIDATION_FAILED_MESSAGE),
	// [500]
	INTERNAL_SERVER_ERROR(500, "INTERNAL_SERVER_ERROR", COMMON_INTERNAL_SERVER_ERROR_MESSAGE),

	// auth domain (JWT)
	ACCESS_TOKEN_EXPIRED(401, "JWT_ACCESS_EXPIRED", AUTH_ACCESS_TOKEN_EXPIRED_MESSAGE),
	ACCESS_TOKEN_INVALID(401, "JWT_ACCESS_INVALID", AUTH_ACCESS_TOKEN_INVALID_MESSAGE),
	REFRESH_TOKEN_EXPIRED(401, "JWT_REFRESH_EXPIRED", AUTH_REFRESH_TOKEN_EXPIRED_MESSAGE),
	REFRESH_TOKEN_INVALID(401, "JWT_REFRESH_INVALID", AUTH_REFRESH_TOKEN_INVALID_MESSAGE),
	MISSING_TOKEN(401, "JWT_MISSING", AUTH_ACCESS_TOKEN_MISSING_MESSAGE),

	// user domain
	AUTH_INVALID_CREDENTIALS(401, "AUTH_INVALID_CREDENTIALS", AUTH_INVALID_CREDENTIALS_MESSAGE),
	USER_NOT_FOUND(404, "USER_NOT_FOUND", USER_NOT_FOUND_MESSAGE),
	ALARM_SETTING_NOT_FOUND(404, "ALARM_SETTING_NOT_FOUND", ALARM_SETTING_NOT_FOUND_MESSAGE),
	CHARACTER_NOT_SET(404, "CHARACTER_NOT_SET", CHARACTER_NOT_SET_MESSAGE),
	USER_EMAIL_DUPLICATED(409, "USER_EMAIL_DUPLICATED", USER_EMAIL_DUPLICATED_MESSAGE),
	USER_NICKNAME_DUPLICATED(409, "USER_NICKNAME_DUPLICATED", USER_NICKNAME_DUPLICATED_MESSAGE),
	CHARACTER_ALREADY_SET(409, "CHARACTER_ALREADY_SET", CHARACTER_ALREADY_SET_MESSAGE),

	// survey domain
	SURVEY_NOT_FOUND(404, "SURVEY_NOT_FOUND", SURVEY_NOT_FOUND_MESSAGE),

	// routine domain
	ROUTINE_NOT_FOUND(404, "ROUTINE_NOT_FOUND", ROUTINE_NOT_FOUND_MESSAGE),

	// image domain
	// [400]
	INVALID_FILE_EXTENSION(400, "INVALID_FILE_EXTENSION", INVALID_FILE_EXTENSION_MESSAGE),
	INVALID_FILE_PATH(400, "INVALID_FILE_PATH", INVALID_FILE_PATH_MESSAGE),
	// [404]
	IMAGE_NOT_FOUND(404, "IMAGE_NOT_FOUND", IMAGE_NOT_FOUND_MESSAGE),
	// [500]
	IMAGE_UPLOAD_FAILED(500, "IMAGE_UPLOAD_FAILED", IMAGE_UPLOAD_FAILED_MESSAGE),
	IMAGE_DELETE_FAILED(500, "IMAGE_DELETE_FAILED", IMAGE_DELETE_FAILED_MESSAGE),
	PRESIGNED_URL_GENERATION_FAILED(500, "PRESIGNED_URL_GENERATION_FAILED", PRESIGNED_URL_GENERATION_FAILED_MESSAGE),

	// exercise domain
	EXERCISE_NOT_FOUND(404, "EXERCISE_NOT_FOUND", EXERCISE_NOT_FOUND_MESSAGE),
	EXERCISE_TYPE_MISMATCH(400, "EXERCISE_TYPE_MISMATCH", EXERCISE_TYPE_MISMATCH_MESSAGE),
	EXERCISE_SESSION_NOT_FOUND(404, "EXERCISE_SESSION_NOT_FOUND", EXERCISE_SESSION_NOT_FOUND_MESSAGE),

	// AI server
	AI_SERVER_CONNECTION_FAILED(503, "AI_SERVER_CONNECTION_FAILED", AI_SERVER_CONNECTION_FAILED_MESSAGE),
	AI_SERVER_TIMEOUT(504, "AI_SERVER_TIMEOUT", AI_SERVER_TIMEOUT_MESSAGE),
	AI_RESPONSE_PARSE_FAILED(500, "AI_RESPONSE_PARSE_FAILED", AI_RESPONSE_PARSE_FAILED_MESSAGE),
	AI_SERVER_ERROR(500, "AI_SERVER_ERROR", AI_SERVER_ERROR_MESSAGE),
	AI_ROUTINE_NOT_COMPLETED(400, "AI_ROUTINE_NOT_COMPLETED", AI_ROUTINE_NOT_COMPLETED_MESSAGE),
	AI_ROUTINE_EMPTY(400, "AI_ROUTINE_EMPTY", AI_ROUTINE_EMPTY_MESSAGE),
	AI_ROUTINE_STEPS_EMPTY(400, "AI_ROUTINE_STEPS_EMPTY", AI_ROUTINE_STEPS_EMPTY_MESSAGE),
	AI_ROUTINE_EXERCISE_ID_MISSING(400, "AI_ROUTINE_EXERCISE_ID_MISSING", AI_ROUTINE_EXERCISE_ID_MISSING_MESSAGE),
	AI_ROUTINE_TARGET_REPS_MISSING(400, "AI_ROUTINE_TARGET_REPS_MISSING", AI_ROUTINE_TARGET_REPS_MISSING_MESSAGE),
	AI_ROUTINE_DURATION_TIME_MISSING(400, "AI_ROUTINE_DURATION_TIME_MISSING", AI_ROUTINE_DURATION_TIME_MISSING_MESSAGE),
	AI_ROUTINE_EYES_INVALID(400, "AI_ROUTINE_EYES_INVALID", AI_ROUTINE_EYES_INVALID_MESSAGE),
	AI_ROUTINE_GENERATION_FAILED(500, "AI_ROUTINE_GENERATION_FAILED", AI_ROUTINE_GENERATION_FAILED_MESSAGE),


	// post domain
	POST_NOT_FOUND(404, "POST_NOT_FOUND", POST_NOT_FOUND_MESSAGE);

	private final int httpStatusCode;
	private final String code;
	private final String reason;

	public boolean isJwtError() {
		return code != null && code.startsWith("JWT_");
	}
}
